spring:
  application:
    name: stegroo-backend
  
  # Inaktivera JPA för att undvika databasfel
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

# Stegroo säkerhetskonfiguration för enkel profil
stegroo:
  security:
    jwt:
      enabled: true
    cors:
      allowed-origins: http://localhost:3000,http://localhost:5173
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      max-age: 3600

# Server konfiguration
server:
  port: 8080
  servlet:
    context-path: /api

# Loggning
logging:
  level:
    root: INFO
    se.stegroo: DEBUG
    org.springframework.web: INFO
