// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwysotlogybsnaehuuee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3eXNvdGxvZ3lic25hZWh1dWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTkwMjMsImV4cCI6MjA3MTI5NTAyM30.RSU8cuoPWOAZ3_7FYBj_PHEvDnWWgc8tankmOEDjH18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});